### ISSUE TITLE
Wrong cursor position when click 

### ISSUE THREAD

**Issue by ojk12** [firejump/vscode-frame-rainbow#5] opened 2023-10-09 18:26 UTC
When you click on the very right of an expression sorrounded by parenthesis, the cursor keeps inside of parenthesis instead of outside

This is the actual behavior
![image](https://github.com/firejump/vscode-frame-rainbow/assets/26471893/ade2c7e1-c783-4ae4-825b-2b4a63b72f21)

This is what should be
![image](https://github.com/firejump/vscode-frame-rainbow/assets/26471893/c0bd457e-51ae-4416-b2ec-7cf7a2611bfc)

When I disable this extensión I have the right behavior

**Comment by firejump** [comment] 2023-12-06 16:57
Duplicate of #1 . Also, this is fixed in 0.1.3. Closing.

**Closed as completed by firejump** 2023-12-06 16:57 UTC
